version: "0.1"
global:
  setup:
    - |
      apt-get update
      apt-get install -y python3-venv
      python3 -m venv venv
      . venv/bin/activate
      pip install pytest 
pipeline:
  runTest:
    exec:
      - |
        source venv/bin/activate
        pytest {{testFilePath}}
settings:
  workingDir: .
  include:
    - "**/*.py"
  testPlacementStrategies:
    - type: regex
      testFilePattern: test_{{sourceFileName}}.py
      testDirPattern: /src/(.*)/g
      testDirReplacement: tests/$1
  language: python
  framework: pytest
